DROP TABLE APACHE_KAFKA_DEFINITION IF EXISTS;
DROP SEQUENCE APACHE_KAFKA_SEQUENCE IF EXISTS;

CREATE TABLE APACHE_KAFKA_DEFINITION
(
 ID NUMBER PRIMARY KEY,
DESCRIPTION VARCHAR(5000),
DETAILS VARCHAR(5000),
IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE APACHE_KAFKA_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE
NOCYCLE;

DROP TABLE CORE_JAVA_DEFINITION IF EXISTS;
DROP SEQUENCE CORE_JAVA_SEQUENCE IF EXISTS;

CREATE TABLE CORE_JAVA_DEFINITION
(
 ID NUMBER PRIMARY KEY,
DESCRIPTION VARCHAR(5000),
DETAILS VARCHAR(5000),
IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE CORE_JAVA_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE
NOCYCLE;

DROP TABLE IBM_MQ_DEFINITION IF EXISTS;
DROP SEQUENCE IBM_MQ_SEQUENCE IF EXISTS;

CREATE TABLE IBM_MQ_DEFINITION
(
 ID NUMBER PRIMARY KEY,
DESCRIPTION VARCHAR(5000),
DETAILS VARCHAR(5000),
IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE IBM_MQ_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE
NOCYCLE;